version: '3.9'

services:
  api:
    build: .
    command: gunicorn
    ports:
      - '15000:5000'
    volumes:
      - gunicorn_sock:/run/gunicorn/
      - ./:/work/
  nginx:
    image: nginx:1.23
    depends_on:
      - api
    volumes:
      - gunicorn_sock:/tmp/gunicorn/
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
volumes:
  gunicorn_sock:
