version: '3.9'

services:
  api:
    build: .
    command: gunicorn
    volumes:
      - gunicorn_sock:/run/gunicorn/
      - ./:/work/
  nginx:
    image: nginx:1.23
    depends_on:
      - api
      - swaggerui
    volumes:
      - gunicorn_sock:/tmp/gunicorn/
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8080:80'
  swaggerui:
    image: swaggerapi/swagger-ui:v4.15.5
    environment:
      - URL=/docs/openapi.yaml
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
volumes:
  gunicorn_sock:
